[buildPlans.carrot-mono]
family = "Carrot Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.carrot-mono.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifed-both-sides"
capital-q = "crossing-baseline"
i = "serifed-asymmetric"
l = "tailed-serifed"
q = "diagonal-tailed-serifless"
w = "straight-flat-top-serifless"
y = "straight-turn-serifless"
zero = "dotted"
two = "straight-neck"
three = "flat-top"
five = "oblique-arched"
eight = "crossing-asymmetric"
ampersand = "upper-open"
dollar = "open"
cent = "open"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.carrot-mono.variants.italic]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "curly-open-serifless"
capital-u = "tailed-serifless"
capital-v = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
f = "tailed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "cursive"
y = "cursive-serifless"
z = "cursive"

[buildPlans.carrot-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.carrot-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.carrot-mono.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


[buildPlans.carrot-term]
family = "Carrot Term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.carrot-term.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifed-both-sides"
capital-q = "crossing-baseline"
i = "serifed-asymmetric"
l = "tailed-serifed"
q = "diagonal-tailed-serifless"
w = "straight-flat-top-serifless"
y = "straight-turn-serifless"
zero = "dotted"
two = "straight-neck"
three = "flat-top"
five = "oblique-arched"
eight = "crossing-asymmetric"
ampersand = "upper-open"
dollar = "open"
cent = "open"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.carrot-term.variants.italic]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-p = "open-serifless"
capital-q = "open-swash"
capital-r = "curly-open-serifless"
capital-u = "tailed-serifless"
capital-v = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
f = "tailed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
v = "cursive-serifless"
w = "cursive-serifless"
x = "cursive"
y = "cursive-serifless"
z = "cursive"

[buildPlans.carrot-term.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.carrot-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.carrot-term.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
