[buildPlans.iosevka-carrot-mono]
family = "Iosevka Carrot Mono"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-carrot-mono.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-q = "crossing"
l = "tailed-serifed"
q = "diagonal-tailed"
w = "straight-flat-top"
y = "straight-turn"
zero = "dotted"
two = "straight-neck"
three = "flat-top"
five = "oblique-upper-left-bar"
eight = "crossing-asymmetric"
dollar = "open"
cent = "open"
partial-derivative = "curly-bar"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.iosevka-carrot-mono.variants.italic]
capital-b = "more-asymmetric-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "descending-serifed"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging"
capital-q = "open-swash"
capital-r = "standing"
capital-u = "tailed"
a = "double-storey-tailed"
b = "toothless-corner"
f = "tailed"
g = "earless-corner"
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "earless-corner"
q = "earless-corner-diagonal-tailed"
v = "cursive"
w = "cursive"
x = "cursive"
y = "cursive"
z = "cursive"

[buildPlans.iosevka-carrot-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-carrot-mono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-carrot-mono.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


[buildPlans.iosevka-carrot-term]
family = "Iosevka Carrot Term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = false

[buildPlans.iosevka-carrot-term.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-q = "crossing"
l = "tailed-serifed"
q = "diagonal-tailed"
w = "straight-flat-top"
y = "straight-turn"
zero = "dotted"
two = "straight-neck"
three = "flat-top"
five = "oblique-upper-left-bar"
eight = "crossing-asymmetric"
dollar = "open"
cent = "open"
partial-derivative = "curly-bar"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.iosevka-carrot-term.variants.italic]
capital-b = "more-asymmetric-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "descending-serifed"
capital-k = "curly-serifless"
capital-m = "slanted-sides-hanging"
capital-q = "open-swash"
capital-r = "standing"
capital-u = "tailed"
a = "double-storey-tailed"
b = "toothless-corner"
f = "tailed"
g = "earless-corner"
h = "tailed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
p = "earless-corner"
q = "earless-corner-diagonal-tailed"
v = "cursive"
w = "cursive"
x = "cursive"
y = "cursive"
z = "cursive"

[buildPlans.iosevka-carrot-term.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-carrot-term.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-carrot-term.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
